language: node_js
sudo: required
addons:
 chrome: stable
node_js:
- '6'
- '7'
- '8'
before_install:
  # Add token
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

  - npm install -g bower
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - bower install
  - npm install
after_script:
  - gulp coveralls

deploy:
  provider: npm
  email: "info@dash.org"
  api_key: $NPM_TOKEN
  on:
    branch: master
